#ifndef ALGORITMOGENETICO_GLOBAL_H
#define ALGORITMOGENETICO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ALGORITMOGENETICO_LIBRARY)
#  define ALGORITMOGENETICOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ALGORITMOGENETICOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ALGORITMOGENETICO_GLOBAL_H
